# Predicting the Price of Energy in Germany

In [ ]:
import pandas as pd 
import numpy as np 
import datetime

In [ ]:
# Data Ingestion 

df = pd.read_csv(r"")
df.head()

,date,country,avg_temperature,humidity,co2_emission,energy_consumption,renewable_share,urban_population,industrial_activity_index,energy_price
0,2020-01-01,Germany,28.29,31.08,212.63,11348.75,14.42,76.39,51.22,83.93
1,2020-01-02,Germany,28.38,37.94,606.05,4166.64,5.63,86.26,78.27,110.40
2,2020-01-03,Germany,28.74,57.67,268.72,4503.80,14.20,75.92,48.96,173.58
3,2020-01-04,Germany,26.66,51.34,167.32,3259.13,13.84,63.15,97.42,89.13
4,2020-01-05,Germany,26.81,65.38,393.89,7023.72,6.93,76.02,81.89,40.60

In [ ]:
# Feature Engineering

df["date"] = pd.to_datetime(df["date"])
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["dayofweek"] = df["date"].dt.dayofweek 
df["is_weekend"] = (df["dayofweek"] >= 5).astype(int)

df["month_sin"] = np.sin(2*np.pi*df["month"]/12)
df["month_cos"] = np.cos(2*np.pi*df["month"]/12)

df["price_(t-1)"] = df["energy_price"].shift(1)
df["price_ma7"] = df["energy_price"].rolling(window=7).mean()
df["price_std7"] = df["energy_price"].rolling(window=7).std()



df.head()

,date,country,avg_temperature,humidity,co2_emission,energy_consumption,renewable_share,urban_population,industrial_activity_index,energy_price,year,month,day,dayofweek,is_weekend
0,2020-01-01,Germany,28.29,31.08,212.63,11348.75,14.42,76.39,51.22,83.93,2020,1,1,2,0
1,2020-01-02,Germany,28.38,37.94,606.05,4166.64,5.63,86.26,78.27,110.40,2020,1,2,3,0
2,2020-01-03,Germany,28.74,57.67,268.72,4503.80,14.20,75.92,48.96,173.58,2020,1,3,4,0
3,2020-01-04,Germany,26.66,51.34,167.32,3259.13,13.84,63.15,97.42,89.13,2020,1,4,5,1
4,2020-01-05,Germany,26.81,65.38,393.89,7023.72,6.93,76.02,81.89,40.60,2020,1,5,6,1

In [5]:
# Data Cleaning 

df = df.dropna()
df = df.drop_duplicates()
df.head()

,date,country,avg_temperature,humidity,co2_emission,energy_consumption,renewable_share,urban_population,industrial_activity_index,energy_price,year,month,day,dayofweek,is_weekend
0,2020-01-01,Germany,28.29,31.08,212.63,11348.75,14.42,76.39,51.22,83.93,2020,1,1,2,0
1,2020-01-02,Germany,28.38,37.94,606.05,4166.64,5.63,86.26,78.27,110.40,2020,1,2,3,0
2,2020-01-03,Germany,28.74,57.67,268.72,4503.80,14.20,75.92,48.96,173.58,2020,1,3,4,0
3,2020-01-04,Germany,26.66,51.34,167.32,3259.13,13.84,63.15,97.42,89.13,2020,1,4,5,1
4,2020-01-05,Germany,26.81,65.38,393.89,7023.72,6.93,76.02,81.89,40.60,2020,1,5,6,1

## Column Statistics

In [6]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
date,36540,NaN,NaN,NaN,2022-07-02 00:00:00,2020-01-01 00:00:00,2021-04-01 00:00:00,2022-07-02 00:00:00,2023-10-02 00:00:00,2024-12-31 00:00:00,NaN
country,36540,20,Germany,1827,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_temperature,36540.0,NaN,NaN,NaN,13.580868,-9.6,5.63,13.79,20.84,38.71,10.077249
humidity,36540.0,NaN,NaN,NaN,59.971469,30.0,45.01,59.99,74.97,90.0,17.303103
co2_emission,36540.0,NaN,NaN,NaN,445.820452,50.15,248.675,422.655,628.4225,999.85,234.360906
energy_consumption,36540.0,NaN,NaN,NaN,7295.904857,1001.89,4184.1775,6921.62,10175.11,15998.05,3693.928504
renewable_share,36540.0,NaN,NaN,NaN,15.94408,5.0,12.02,15.715,19.84,30.87,5.334804
urban_population,36540.0,NaN,NaN,NaN,74.982156,60.0,67.47,75.03,82.5025,90.0,8.6454
industrial_activity_index,36540.0,NaN,NaN,NaN,70.173094,40.0,55.3,70.055,85.26,100.0,17.334816
energy_price,36540.0,NaN,NaN,NaN,115.279848,30.0,72.42,115.24,158.27,200.0,49.178361
year,36540.0,NaN,NaN,NaN,2022.0,2020.0,2021.0,2022.0,2023.0,2024.0,1.415007
month,36540.0,NaN,NaN,NaN,6.521073,1.0,4.0,7.0,10.0,12.0,3.44926
day,36540.0,NaN,NaN,NaN,15.735085,1.0,8.0,16.0,23.0,31.0,8.802512
dayofweek,36540.0,NaN,NaN,NaN,3.0,0.0,1.0,3.0,5.0,6.0,2.000027
is_weekend,36540.0,NaN,NaN,NaN,0.285714,0.0,0.0,0.0,1.0,1.0,0.45176